#Select top people ranked by RDFRank

PREFIX imdb: <http://example.org/movieDB/>
PREFIX rank: <http://www.ontotext.com/owlim/RDFRank#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT * where { 
    ?p a foaf:Person ; foaf:name ?name.
    ?p rank:hasRDFRank5 ?r .
} ORDER BY DESC(?r)