#Federated query with FactForge.net to obtain actor's relatives
#Infer new facts for relatives

PREFIX imdb: <http://example.org/movieDB/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

#replace with INSERT
CONSTRUCT {
    #GRAPH imdb:dbp_relatives { #uncomment the graph when inserting data
    ?dbp_actor ?p ?relative 
	#}  #uncomment when inserting data
}
WHERE {
    GRAPH imdb:dbp_matching {?actor skos:exactMatch ?dbp_actor}
    SERVICE <http://factforge.net/repositories/ff-news> {
        ?dbp_actor ?p ?relative . filter(?p in (dbo:child, dbo:parent, dbo:spouse))
    }
} LIMIT 100 #remove the limit when inserting
