# Let's introduce a new property hasActor and see what kind of inference it will produce (RDFS & OWL)

@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> . 
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix imdb: <http://example.org/movieDB/> .

	imdb:leadActor rdfs:subPropertyOf imdb:hasActor .
	imdb:2ndActor rdfs:subPropertyOf imdb:hasActor .
	imdb:3rdActor rdfs:subPropertyOf imdb:hasActor .
	imdb:Director rdfs:subClassOf foaf:Person .
	imdb:Actor rdfs:subClassOf foaf:Person .
	imdb:hasActor owl:inverseOf imdb:actsIn .
	imdb:directedBy owl:inverseOf imdb:directs . 
