prefix spif: <http://spinrdf.org/spif#>
prefix mdb: <http://example.org/movieDB/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
# An INSERT query that maps the raw RDF data from OntoRefine to user-specified
# RDF data (different IRIs, types, property names and dates as date-typed literals)
# and inserts the data into the current GraphDB repository.
CONSTRUCT {#graph <http://example.org/movieDB/> {
    ?movieIRI a mdb:Movie ;
        mdb:title ?title ;
        mdb:color ?color ;
		mdb:directedBy ?directorIRI ;
		mdb:numCritics ?numCritics;
		mdb:duration ?duration;
		mdb:leadActor ?actor1IRI;
		mdb:2ndActor ?actor2IRI;
		mdb:3rdActor ?actor3IRI;
		mdb:gross ?gross;
		mdb:numUserVotes ?numUserVotes;
		mdb:numUserReviews ?numUserReviews;
		mdb:castTotalFBLikes ?castTotalFBLikes;
		mdb:numFacesInPoster ?numFacesInPoster;
		rdf:about ?imdbURL;
		mdb:language ?language;
		mdb:country ?countryIRI;
		mdb:contentRating ?contentRating;
		mdb:budget ?budget;
		mdb:year ?year;
		mdb:imdbScore ?imdbScore;
		mdb:aspectRatio ?aspectRatio;
		mdb:movieFBLikes ?movieFBLikes;
		mdb:keyword ?keyword1, ?keyword2, ?keyword3, ?keyword4, ?keyword5;
		mdb:genre ?genres1, ?genres2, ?genres3, ?genres4, ?genres5, ?genres6, ?genres7, ?genres8.
	?directorIRI a mdb:Director ;
		foaf:name ?directorName;
		mdb:directorFBLikes ?directorFBLikes.
	?actor1IRI a mdb:Actor;
		foaf:name ?actor1Name;
		mdb:actorFBLikes ?actor1FBLikes.
	?actor2IRI a mdb:Actor;
		foaf:name ?actor2Name;
		mdb:actorFBLikes ?actor2FBLikes.
	?actor3IRI a mdb:Actor;
		foaf:name ?actor3Name;
		mdb:actorFBLikes ?actor3FBLikes.
    ?countryIRI a mdb:Country;
        rdfs:label ?country.
    #}
} where {
    # Uses SERVICE to fetch the raw RDF data from OntoRefine
    
        ?movieRow a mdb:Row ;
		mdb:rowNumber ?movieRowNumber.
        OPTIONAL {?movieRow mdb:color ?color}
        OPTIONAL {?movieRow mdb:director_name ?directorName}
		OPTIONAL {?movieRow mdb:director ?director}
        OPTIONAL {?movieRow mdb:num_critic_for_reviews ?numCritics }
		OPTIONAL {?movieRow mdb:duration ?duration}
		OPTIONAL {?movieRow mdb:director_facebook_likes ?directorFBLikes}
		OPTIONAL {?movieRow mdb:actor_1_facebook_likes ?actor1FBLikes}
		OPTIONAL {?movieRow mdb:actor_2_facebook_likes ?actor2FBLikes}
		OPTIONAL {?movieRow mdb:actor_3_facebook_likes ?actor3FBLikes}
		OPTIONAL {?movieRow mdb:actor_1_name ?actor1Name}
		OPTIONAL {?movieRow mdb:actor_2_name ?actor2Name}
		OPTIONAL {?movieRow mdb:actor_3_name ?actor3Name}
        OPTIONAL {?movieRow mdb:actor_1 ?actor1}
		OPTIONAL {?movieRow mdb:actor_2 ?actor2}
		OPTIONAL {?movieRow mdb:actor_3 ?actor3}
		OPTIONAL {?movieRow mdb:gross ?gross}
		OPTIONAL {?movieRow mdb:movie_title ?title}
		OPTIONAL {?movieRow mdb:num_voted_users ?numUserVotes}
		OPTIONAL {?movieRow mdb:cast_total_facebook_likes ?castTotalFBLikes}
		OPTIONAL {?movieRow mdb:facenumber_in_poster ?numFacesInPoster}
		OPTIONAL {?movieRow mdb:movie_imdb_link ?imdb}
		OPTIONAL {?movieRow mdb:num_user_for_reviews ?numUserReviews}
		OPTIONAL {?movieRow mdb:language ?language}
		OPTIONAL {?movieRow mdb:country ?country}
		OPTIONAL {?movieRow mdb:content_rating ?contentRating}
		OPTIONAL {?movieRow mdb:budget ?budget}
		OPTIONAL {?movieRow mdb:title_year ?year}
		OPTIONAL {?movieRow mdb:imdb_score ?imdbScore}
		OPTIONAL {?movieRow mdb:aspect_ratio ?aspectRatio}
		OPTIONAL {?movieRow mdb:movie_facebook_likes ?movieFBLikes}
		OPTIONAL {?movieRow mdb:plot_keywords_1 ?keyword1}
		OPTIONAL {?movieRow mdb:plot_keywords_2 ?keyword2}
		OPTIONAL {?movieRow mdb:plot_keywords_3 ?keyword3}
		OPTIONAL {?movieRow mdb:plot_keywords_4 ?keyword4}
		OPTIONAL {?movieRow mdb:plot_keywords_5 ?keyword5}
		OPTIONAL {?movieRow mdb:genres_1 ?genres1}
		OPTIONAL {?movieRow mdb:genres_2 ?genres2}
		OPTIONAL {?movieRow mdb:genres_3 ?genres3}
		OPTIONAL {?movieRow mdb:genres_4 ?genres4}
		OPTIONAL {?movieRow mdb:genres_5 ?genres5}
		OPTIONAL {?movieRow mdb:genres_6 ?genres6}
		OPTIONAL {?movieRow mdb:genres_7 ?genres7}
		OPTIONAL {?movieRow mdb:genres_8 ?genres8}
    
    bind(iri(concat("http://example.org/movieDB/movie/", spif:encodeURL(?movieRowNumber))) as ?movieIRI).
    bind(iri(concat("http://example.org/movieDB/person/", spif:encodeURL(?director))) as ?directorIRI).
    bind(iri(concat("http://example.org/movieDB/person/", spif:encodeURL(?actor1))) as ?actor1IRI).
    bind(iri(concat("http://example.org/movieDB/person/", spif:encodeURL(?actor2))) as ?actor2IRI).
    bind(iri(concat("http://example.org/movieDB/person/", spif:encodeURL(?actor3))) as ?actor3IRI).
    bind(iri(concat("http://example.org/movieDB/country/", spif:encodeURL(?country))) as ?countryIRI).
	bind(iri(?imdb) as ?imdbURL).
} LIMIT 100